name: cicd

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: version docker
        run: sudo docker -v
      - name: conteners running
        run: sudo docker ps
      - name: install docker compose
        run: sudo apt-get install -y docker-compose
      - name: version docker compose
        run: sudo docker-compose -v
      - name: Checkout code
        uses: actions/checkout@v5
      - name: build and run docker compose
        run: sudo docker compose up -d