name: cicd

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: version docker
        run: sudo docker -v
      - name: conteners running
        run: sudo docker ps
      - name: install docker
        run: sudo apt-get update && sudo apt-get install -y docker.io
      - name: install docker compose
        run: sudo apt-get install -y docker-compose